-- ====================================
-- SALES REP DIRECTORY - SUPABASE SCHEMA
-- ====================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ====================================
-- COMPANIES TABLE
-- ====================================
create table public.companies (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  logo_url text,
  description text,
  category text,
  slug text unique not null
);

-- Enable RLS
alter table public.companies enable row level security;

-- Allow public read access to companies
create policy "Companies are viewable by everyone"
  on public.companies for select
  using (true);

-- ====================================
-- PROFILES TABLE
-- ====================================
create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  created_at timestamptz default now(),
  first_name text,
  last_name text,
  profile_picture_url text,
  bio text,
  city text,
  state text,
  zip_code text,
  personal_website_url text,
  is_pro_subscriber boolean default false,
  stripe_customer_id text,
  constraint proper_state_code check (state is null or length(state) = 2),
  constraint proper_zip_code check (zip_code is null or length(zip_code) = 5)
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Profiles are viewable by everyone
create policy "Profiles are viewable by everyone"
  on public.profiles for select
  using (true);

-- Users can insert their own profile
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- ====================================
-- REP_COMPANIES JOIN TABLE
-- ====================================
create table public.rep_companies (
  id bigint generated by default as identity primary key,
  rep_id uuid references public.profiles(id) on delete cascade,
  company_id bigint references public.companies(id) on delete cascade,
  created_at timestamptz default now(),
  unique(rep_id, company_id)
);

-- Enable RLS
alter table public.rep_companies enable row level security;

-- Rep companies are viewable by everyone
create policy "Rep companies are viewable by everyone"
  on public.rep_companies for select
  using (true);

-- Users can manage their own company associations
create policy "Users can insert own rep companies"
  on public.rep_companies for insert
  with check (auth.uid() = rep_id);

create policy "Users can delete own rep companies"
  on public.rep_companies for delete
  using (auth.uid() = rep_id);

-- ====================================
-- REVIEWS TABLE
-- ====================================
create table public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  rep_id uuid references public.profiles(id) on delete cascade,
  reviewer_name text not null,
  rating int not null,
  comment text,
  is_approved boolean default false,
  constraint valid_rating check (rating >= 1 and rating <= 5)
);

-- Enable RLS
alter table public.reviews enable row level security;

-- Only approved reviews are viewable by public
create policy "Approved reviews are viewable by everyone"
  on public.reviews for select
  using (is_approved = true);

-- Anyone can insert a review (it will be unapproved by default)
create policy "Anyone can submit a review"
  on public.reviews for insert
  with check (true);

-- ====================================
-- FUNCTIONS & TRIGGERS
-- ====================================

-- Function to create profile on user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name'
  );
  return new;
end;
$$;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ====================================
-- INDEXES FOR PERFORMANCE
-- ====================================
create index profiles_city_idx on public.profiles(city);
create index profiles_state_idx on public.profiles(state);
create index profiles_zip_code_idx on public.profiles(zip_code);
create index profiles_pro_subscriber_idx on public.profiles(is_pro_subscriber);
create index rep_companies_rep_id_idx on public.rep_companies(rep_id);
create index rep_companies_company_id_idx on public.rep_companies(company_id);
create index reviews_rep_id_idx on public.reviews(rep_id);
create index reviews_approved_idx on public.reviews(is_approved);
create index companies_slug_idx on public.companies(slug);

-- ====================================
-- STORAGE BUCKET FOR PROFILE PICTURES
-- ====================================

-- Create storage bucket
insert into storage.buckets (id, name, public)
values ('profile-pictures', 'profile-pictures', true);

-- Allow public read access
create policy "Profile pictures are publicly accessible"
  on storage.objects for select
  using (bucket_id = 'profile-pictures');

-- Allow authenticated users to upload their own pictures
create policy "Users can upload their own profile pictures"
  on storage.objects for insert
  with check (
    bucket_id = 'profile-pictures'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- Allow authenticated users to update their own pictures
create policy "Users can update their own profile pictures"
  on storage.objects for update
  using (
    bucket_id = 'profile-pictures'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- Allow authenticated users to delete their own pictures
create policy "Users can delete their own profile pictures"
  on storage.objects for delete
  using (
    bucket_id = 'profile-pictures'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ====================================
-- SEED DATA - SAMPLE COMPANIES
-- ====================================

insert into public.companies (name, logo_url, description, category, slug) values
  ('Mary Kay', null, 'Beauty and cosmetics direct sales company', 'Cosmetics', 'mary-kay'),
  ('Pampered Chef', null, 'Kitchen tools, food products, and cookbooks', 'Kitchenware', 'pampered-chef'),
  ('Avon', null, 'Beauty, household, and personal care products', 'Cosmetics', 'avon'),
  ('Tupperware', null, 'Kitchen and home products', 'Kitchenware', 'tupperware'),
  ('Scentsy', null, 'Scented candles, wax warmers, and home fragrance products', 'Home Fragrance', 'scentsy'),
  ('doTERRA', null, 'Essential oils and wellness products', 'Wellness', 'doterra'),
  ('Young Living', null, 'Essential oils and wellness products', 'Wellness', 'young-living'),
  ('Norwex', null, 'Environmentally friendly cleaning products', 'Cleaning', 'norwex'),
  ('Rodan + Fields', null, 'Skincare and beauty products', 'Cosmetics', 'rodan-fields'),
  ('Arbonne', null, 'Health, wellness, and skincare products', 'Wellness', 'arbonne');

-- ====================================
-- EXTERNAL LISTINGS TABLE
-- ====================================
-- Stores listings from external sources (Google Maps, etc.)
-- These are not tied to authenticated users

create table public.external_listings (
  id text primary key,
  created_at timestamptz default now(),
  title text not null,
  first_name text,
  last_name text,
  total_score decimal(2,1),
  reviews_count int default 0,
  street text,
  city text,
  state text,
  country_code text default 'US',
  website text,
  phone text,
  category_name text,
  google_maps_url text,
  company_slug text references public.companies(slug),
  source text default 'google-maps',
  is_active boolean default true
);

-- Enable RLS
alter table public.external_listings enable row level security;

-- External listings are viewable by everyone
create policy "External listings are viewable by everyone"
  on public.external_listings for select
  using (is_active = true);

-- Indexes for performance
create index external_listings_company_slug_idx on public.external_listings(company_slug);
create index external_listings_state_idx on public.external_listings(state);
create index external_listings_city_idx on public.external_listings(city);
create index external_listings_active_idx on public.external_listings(is_active);
