-- ====================================
-- PROFILE ENHANCEMENTS
-- ====================================
-- Add new fields for enhanced rep cards

-- Add email verification tracking
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false;

-- Add response time tracking (average hours to respond)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avg_response_hours numeric(5,1);

-- Add coordinates for distance calculation
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS latitude numeric(10,7);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS longitude numeric(10,7);

-- Create index for geographic queries
CREATE INDEX IF NOT EXISTS profiles_location_idx ON public.profiles(latitude, longitude) WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

-- ====================================
-- SUBSCRIPTION MANAGEMENT
-- ====================================
-- Add fields for annual billing and subscription management

-- Add subscription type tracking
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_type text DEFAULT 'free' CHECK (subscription_type IN ('free', 'pro_monthly', 'pro_annual'));

-- Add subscription dates
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_start_date timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_end_date timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS trial_end_date timestamptz;

-- Add Stripe price ID for the current subscription
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS stripe_price_id text;

-- Create subscription history table for tracking changes
CREATE TABLE IF NOT EXISTS public.subscription_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  profile_id uuid references public.profiles(id) on delete cascade,
  action text not null check (action in ('upgrade', 'downgrade', 'cancel', 'renew', 'trial_start', 'trial_end')),
  from_plan text,
  to_plan text,
  stripe_subscription_id text,
  metadata jsonb default '{}'::jsonb
);

-- Enable RLS on subscription history
ALTER TABLE public.subscription_history ENABLE ROW LEVEL SECURITY;

-- Users can view their own subscription history
CREATE POLICY "Users can view own subscription history"
  ON public.subscription_history FOR SELECT
  USING (auth.uid() = profile_id);

-- Service role can insert
CREATE POLICY "Service role can insert subscription history"
  ON public.subscription_history FOR INSERT
  WITH CHECK (true);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS subscription_history_profile_id_idx ON public.subscription_history(profile_id);
CREATE INDEX IF NOT EXISTS subscription_history_created_at_idx ON public.subscription_history(created_at DESC);

-- ====================================
-- HELPER FUNCTIONS
-- ====================================

-- Function to calculate distance between two points (in miles)
CREATE OR REPLACE FUNCTION public.calculate_distance_miles(
  lat1 numeric,
  lon1 numeric,
  lat2 numeric,
  lon2 numeric
)
RETURNS numeric
LANGUAGE plpgsql
AS $$
DECLARE
  r numeric := 3959; -- Earth's radius in miles
  dlat numeric;
  dlon numeric;
  a numeric;
  c numeric;
BEGIN
  IF lat1 IS NULL OR lon1 IS NULL OR lat2 IS NULL OR lon2 IS NULL THEN
    RETURN NULL;
  END IF;

  dlat := radians(lat2 - lat1);
  dlon := radians(lon2 - lon1);

  a := sin(dlat / 2) * sin(dlat / 2) +
       cos(radians(lat1)) * cos(radians(lat2)) *
       sin(dlon / 2) * sin(dlon / 2);

  c := 2 * atan2(sqrt(a), sqrt(1 - a));

  RETURN r * c;
END;
$$;

-- Function to find reps within a radius
CREATE OR REPLACE FUNCTION public.find_reps_within_radius(
  user_lat numeric,
  user_lon numeric,
  radius_miles numeric
)
RETURNS TABLE (
  profile_id uuid,
  distance_miles numeric
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id as profile_id,
    public.calculate_distance_miles(user_lat, user_lon, p.latitude, p.longitude) as distance_miles
  FROM public.profiles p
  WHERE p.latitude IS NOT NULL
    AND p.longitude IS NOT NULL
    AND public.calculate_distance_miles(user_lat, user_lon, p.latitude, p.longitude) <= radius_miles
  ORDER BY distance_miles ASC;
END;
$$;
