-- ====================================
-- EMAIL LOGS TABLE
-- ====================================
-- This table stores all email sending activity for tracking and debugging

create table public.email_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  email_type text not null,
  recipient text not null,
  user_id uuid references auth.users(id) on delete set null,
  success boolean not null,
  message_id text,
  error_message text,
  metadata jsonb default '{}'::jsonb,

  -- Add constraint for valid email types
  constraint valid_email_type check (
    email_type in (
      'welcome',
      'profile-reminder',
      'upgrade-pro',
      'subscription-confirmed',
      'review-notification',
      'trial-ending',
      'custom'
    )
  )
);

-- Enable RLS
alter table public.email_logs enable row level security;

-- Only admins can view email logs (no public policy)
-- Users can view their own email logs
create policy "Users can view their own email logs"
  on public.email_logs for select
  using (auth.uid() = user_id);

-- Service role can insert logs (server-side only)
create policy "Service role can insert email logs"
  on public.email_logs for insert
  with check (true);

-- Create indexes for common queries
create index email_logs_email_type_idx on public.email_logs(email_type);
create index email_logs_recipient_idx on public.email_logs(recipient);
create index email_logs_user_id_idx on public.email_logs(user_id);
create index email_logs_created_at_idx on public.email_logs(created_at desc);
create index email_logs_success_idx on public.email_logs(success);

-- Create a function to clean up old logs (optional, run via cron)
create or replace function public.cleanup_old_email_logs(days_to_keep int default 90)
returns int
language plpgsql
security definer
as $$
declare
  deleted_count int;
begin
  delete from public.email_logs
  where created_at < now() - (days_to_keep || ' days')::interval;

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
